### ISSUE TITLE
Hostnames with . causes fuzzer to not start

### ISSUE THREAD

**Issue by BarneyL** [richo/roving#1]
Trying to run the example target on my machine gives me the following error message from the fuzzer:
afl-fuzz 1.83b by <lcamtuf@google.com>

[-] PROGRAM ABORT : Non-alphanumeric fuzzer ID specified via -S or -M
         Location : fix_up_sync(), afl-fuzz.c:7027

This is due to the hostname of my machine having the pattern xxx.yyy.com which makes the fuzzer ID look something like xxx.yyy.com-c46a. If I remove the periods, the fuzzer accepts the fuzzer IDs.

(This might actually be something that should be fixed in the fuzzer since I would have assumed periods to be valid if - is valid, but thought it might be good to have a workaround for the time being.)

**Comment by BarneyL** [comment]
Also encountered some hostnames being longer than the 32 characters that AFL accepts for fuzzer ID.

**Comment by richo** [comment]
oh hey, I'm so sorry I didn't see these emails D:

Oof, yeah that's not idea. I think ideally I'd like to preserve some of the hostname, but I'll get a fix for this today.
