### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by cxht** [richo/roving#15]
Hi~! When I build the client ,error  shows 
root@cszx:/roving# bazel build //cmd/client
ERROR: /roving/WORKSPACE:15:1: file '@bazel_gazelle//:deps.bzl' does not contain symbol 'go_repository'
ERROR: /roving/WORKSPACE:18:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
ERROR: /roving/WORKSPACE:24:1: name 'go_repository' is not defined (did you mean 'local_repository'?)
....
How can I solve this problem?
Thank you !

**Comment by richo** [comment]
Hrm, good question! It looks like something might have moved under us. I'll see what I can sort out and get back to you.

**Comment by richo** [comment]
I made a little progress, but it still appears that stuff is broken underneath us.

Building the client works using the regular go toolchain with a little massaging, however the server expects to have it's templates injected by bazel.

**Comment by richo** [comment]
Hi @cxht on the offchance you're still playing along at home, I believe this is fixed now!
